website/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, Response, request
from ..models import Proposal,ClassEvent, Class, User
from flask_login import login_required, current_user
from ..users.utils import elligible, Qson, roleRequired
from flask_mail import Message
from sqlalchemy import desc,text
from .. import db, mail


main = Blueprint('main', __name__)

@main.route('/home', methods=['GET', 'POST'])
@main.route('/index', methods=['GET', 'POST'])
@main.route('/', methods=['GET', 'POST'])
@login_required
@elligible(current_user)
def home():
    if request.method == 'POST':
        key = request.form.get('search')
        proposals = Proposal.query.from_statement(text(f"""
                                                        SELECT * 
                                                        FROM proposal 
                                                        WHERE name LIKE '%{key}%' 
                                                        OR description LIKE '%{key}%' 
                                                        OR starting_date LIKE '%{key}%'
                                                        OR ending_date LIKE '%{key}%'
                                                        OR date_created LIKE '%{key}%'
                                                        OR proposal_status LIKE '%{key}%'
                                                        ORDER BY date_created DESC
                                                        LIMIT 6;
                                                        """)).all()
        events = ClassEvent.query.filter_by(user_id=current_user.id).order_by(desc(ClassEvent.starting_date)).limit(3).all()
        unreadproposals = len(Proposal.query.filter_by(proposal_status='pending').all())
        unreadevents = len(ClassEvent.query.filter_by(event_status='pending').all())
        classes = Class.query.all()
        return render_template('Index.html', user=current_user, proposals=proposals, events=events, unreadproposals=unreadproposals, unreadevents=unreadevents, classes=classes)
    elif request.method == 'GET':
        unreadproposals = len(Proposal.query.filter_by(proposal_status='pending').all())
        unreadevents = len(ClassEvent.query.filter_by(event_status='pending').all())
        proposals = Proposal.query.filter_by(user_id=current_user.id).order_by(desc(Proposal.date_created)).limit(6).all()
        classes = Class.query.all()
        events = ClassEvent.query.filter_by(user_id=current_user.id).order_by(desc(ClassEvent.starting_date)).limit(3).all()
    return render_template('Index.html', user=current_user, proposals=proposals, events=events, unreadproposals=unreadproposals, unreadevents=unreadevents, classes=classes)

    
@main.route("/catalog/proposals")
@login_required
@elligible(current_user)
def catalogproposals():
    unreadproposals = len(Proposal.query.filter_by(proposal_status='pending').all())
    unreadevents = len(ClassEvent.query.filter_by(event_status='pending').all())
    return render_template("proposalscatalog.html", user=current_user, unreadproposals=unreadproposals, unreadevents=unreadevents)
    
@main.route("/catalog/events")
@login_required
@elligible(current_user)
def catalogevents():
    unreadproposals = len(Proposal.query.filter_by(proposal_status='pending').all())
    unreadevents = len(ClassEvent.query.filter_by(event_status='pending').all())
    return render_template("eventscatalog.html", user=current_user, unreadproposals=unreadproposals, unreadevents=unreadevents)
    
    
def sendapprovalemail(user):
    msg = Message(
        'Registration approved', 
        sender='noreply@demo.com',
        recipients=[user.email]
    )
    
    msg.body =f'''Our administrators have determined that you fit our requirements and aproved your account you can login with the link below:\n
{url_for('users.login', _external=True)}
    '''

    mail.send(msg)    

@main.route('/ajax/proposals')
@login_required
def ajaxproposals():
    proposals = Proposal.query.filter_by(user_id=current_user.id)
    return Qson(proposals)

@main.route('/ajax/events')
@login_required
def ajaxevents():
    events = ClassEvent.query.filter_by(user_id=current_user.id)
    return Qson(events)

website/proposals/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, abort
from werkzeug.security import generate_password_hash
from flask_login import login_required, current_user
from ..users.utils import elligible
from .forms import ProposalForm
from ..models import Proposal, ClassEvent
from .. import db
from sqlalchemy import func, text

proposals = Blueprint('proposals', __name__)

@proposals.route("/create", methods=['GET', 'POST'])
@login_required
@elligible(current_user)
def createnew():
    form = ProposalForm()
    unreadproposals = len(Proposal.query.filter_by(proposal_status='pending').all())
    unreadevents = len(ClassEvent.query.filter_by(event_status='pending').all())
    if form.validate_on_submit():
        if form.starting_date.data and form.ending_date.data:
            print(form.starting_date.data)
            proposal = Proposal(
                name=form.name.data, 
                description=form.description.data, 
                starting_date=form.starting_date.data, 
                ending_date=form.ending_date.data, 
                date_created=func.now(), 
                proposal_status='Pending', 
                user_id=current_user.id
            )
            db.session.add(proposal)
            db.session.commit()
            flash('Proposal created successfully!', category='success')
            return redirect(url_for('main.home'))
        else:
            proposal = Proposal(
                name=form.name.data, 
                description=form.description.data, 
                starting_date=form.starting_date.data, 
                ending_date=form.ending_date.data, 
                date_created=func.now(), 
                proposal_status='Draft', 
                user_id=current_user.id
            )
            db.session.add(proposal)
            db.session.commit()
            flash('Proposal draft created successfully!', category='success')
            return redirect(url_for('main.home'))
    return render_template("documentCreateForm.html", user=current_user, form=form, legend='New Proposal', unreadevents=unreadevents, unreadproposals=unreadproposals)



    
@proposals.route('/proposal/<int:proposal_id>', methods=['GET', 'POST'])
@login_required
@elligible(current_user)
def proposal(proposal_id):
    unreadproposals = len(Proposal.query.filter_by(proposal_status='pending').all())
    unreadevents = len(ClassEvent.query.filter_by(event_status='pending').all())
    proposal = Proposal.query.get_or_404(proposal_id)
    if proposal.user_id != current_user.id and current_user.role != 'Admin' and current_user.role != 'Manager':
        abort(403)
    proposal = Proposal.query.get_or_404(proposal_id)
    if request.method == 'POST':
        if request.form['select'] == 'Approve':
            proposal.proposal_status = 'Approved'
            db.session.commit()
        elif request.form['select'] == 'Reject':
            proposal.proposal_status = 'Rejected'
            db.session.commit()
    return render_template('proposal.html', user=current_user, proposal=proposal, unreadevents=unreadevents, unreadproposals=unreadproposals)
    
@proposals.route('/proposal/<int:proposal_id>/update', methods=['GET', 'POST'])
@login_required
@elligible(current_user)
def proposalUpdate(proposal_id):
    unreadproposals = len(Proposal.query.filter_by(proposal_status='pending').all())
    unreadevents = len(ClassEvent.query.filter_by(event_status='pending').all())
    proposal = Proposal.query.get_or_404(proposal_id)
    if proposal.proposal_status == 'Approved':
        flash('This proposal was approved by administration you cannot update it anymore!', category='error')
        return redirect(url_for('main.home'))
    if proposal.user_id != current_user.id and current_user.role != 'Admin' and current_user.role != 'Manager':
        abort(403)
    else:
        form = ProposalForm()
        if form.validate_on_submit():
            proposal.name = form.name.data
            proposal.description = form.description.data
            proposal.starting_date = form.starting_date.data
            proposal.ending_date = form.ending_date.data
            if form.starting_date.data and form.starting_date.data:
                proposal.proposal_status = 'Pending'
            db.session.commit()
            flash('Proposal'+ str(proposal.name) + ' was updated!', category='success')
            return redirect(url_for('proposals.proposal', proposal_id=proposal.id))
        elif request.method == 'GET':
            form.name.data = proposal.name
            form.description.data = proposal.description
            form.starting_date.data = proposal.starting_date
            form.ending_date.data = proposal.ending_date
        return render_template("documentCreateForm.html", user=current_user, form=form, legend='Update Proposal', unreadevents=unreadevents, unreadproposals=unreadproposals)

@proposals.route('/proposal/<int:proposal_id>/delete', methods=['POST'])
@login_required
@elligible(current_user)
def proposalDelete(proposal_id):
    proposal = Proposal.query.get_or_404(proposal_id)
    if proposal.user_id != current_user.id:
        abort(403)
    db.session.delete(proposal)
    db.session.commit()
    flash('Proposal was deleted!', category='success')
    return redirect(url_for('main.home'))

@proposals.route('/managerproposalview', methods=['GET', 'POST'])
@login_required
@elligible(current_user)
def managerproposalview():
    if request.method == 'POST':
        key = request.form['search']
        print(key)
        if key != '':
            proposals = Proposal.query.from_statement(text(f"""
                                                            SELECT * 
                                                            FROM proposal 
                                                            WHERE name LIKE '%{key}%' 
                                                            OR description LIKE '%{key}%' 
                                                            OR starting_date LIKE '%{key}%'
                                                            OR ending_date LIKE '%{key}%'
                                                            OR date_created LIKE '%{key}%'
                                                            AND proposal_status = 'Pending';
                                                            """)).all()
        else:
            proposals = Proposal.query.filter_by(proposal_status='Pending').all()
        unreadproposals = len(Proposal.query.filter_by(proposal_status='pending').all())
        unreadevents = len(ClassEvent.query.filter_by(event_status='pending').all())
        view = 'proposals'
        return render_template('managerview.html', user=current_user, view=view, data=proposals, unreadevents=unreadevents, unreadproposals=unreadproposals)
    
    unreadproposals = len(Proposal.query.filter_by(proposal_status='pending').all())
    unreadevents = len(ClassEvent.query.filter_by(event_status='pending').all())
    view = 'proposals'
    proposals = Proposal.query.filter_by(proposal_status='Pending').all()
    return render_template('managerview.html', user=current_user, view=view, data=proposals, unreadevents=unreadevents, unreadproposals=unreadproposals)

website/users/routes.py
from .forms import LoginForm, RegistrationForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from ..users.utils import elligible, save_picture, sendEmail
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from ..models import User, Proposal, ClassEvent
from .. import db

users = Blueprint('users', __name__)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash('You are already logged in!')
        return redirect(url_for('main.home'))
    
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                login_user(user, remember=form.remember.data)
                if user.registered:
                    flash('Logged in successfully!', category='success')
                    if user.role == 'Admin':
                        return redirect(url_for('admin.index'))
                    return redirect(url_for('main.home'))
                else:
                    return redirect(url_for('users.registered'))
            else:
                flash('Incorect user details!', category='error')
        else:
            flash('User doesn\'t exist!', category='error')
            
    return render_template('login.html', user=current_user, form=form)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))

@users.route('/signup', methods=['GET', 'POST'])
@users.route('/register', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        flash('You are already registered in!')
        return redirect(url_for('main.home'))
    
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(
            name=form.name.data,
            surname=form.surname.data,
            email=form.email.data, 
            password=generate_password_hash(form.password.data, method='sha256'),
            phone=form.phone.data
        )
        db.session.add(new_user)
        db.session.commit()
        admin = User.query.filter_by(role='Admin').first()
        sendEmail(
            recipients=[admin.email],
            title='New User Registered',
            email_type='Notify_admin_about_new_user',
            user=new_user
        )
        flash('Account created successfully!', category ='success')
        login_user(new_user)
        return redirect(url_for('users.registered'))  
    
    return render_template('register.html', user=current_user, form=form)

@users.route('/user', methods=['GET', 'POST'])
@login_required
def user():
    unreadproposals = len(Proposal.query.filter_by(proposal_status='pending').all())
    unreadevents = len(ClassEvent.query.filter_by(event_status='pending').all())
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.profile_picture = picture_file
        current_user.name = form.name.data
        current_user.surname = form.surname.data
        current_user.email = form.email.data
        current_user.phone = form.phone.data
        db.session.commit()
        flash('Your account has been updated!', category='success')
        return redirect(url_for('users.user'))
    elif request.method == 'GET':
        form.name.data = current_user.name
        form.surname.data = current_user.surname
        form.email.data = current_user.email
        form.phone.data = current_user.phone
    profile_picture = url_for('static', filename='images/profile_pictures/'+ current_user.profile_picture)
    return render_template('UserProfile.html', user=current_user, profile_picture=profile_picture, form=form, unreadevents=unreadevents, unreadproposals=unreadproposals)
    
    
@users.route('/registered')
@login_required
def registered():
    if current_user.registered:
        flash('You are already registered.')
        return redirect(url_for('main.home'))
    return render_template('registered.html', user=current_user)

@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        sendEmail(
            [user.email],
            title='Password reset request',
            email_type='Password_reset',
            user=user)
        flash('An email has been sent with instructions to reset your password.', category='info')
        return redirect(url_for('users.login'))
    
    return render_template('reset_request.html', form=form, user=current_user)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    user= User.verify_reset_token(token)
    if not user:
        flash('That token is invalid or expired', category='warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        password=generate_password_hash(form.password.data, method='sha256'),
        user.password = password
        db.session.commit()
        flash('Your password has been updated!', category ='success')
        return redirect(url_for('users.login'))  
         
    return render_template('reset_token.html', form=form, user=current_user)

website/templates/Index.html
{% extends "main.html" %}
{% block title %} Home {% endblock %}
{% block content %}


<div class="dashbordPrasymuCards column">
    <ul class="list-inline panel-heading text-center">
        <li class="list-inline-item">
            <h3 class="panel-title">
                Recent Proposals
            </h3>
        </li>
        <li class="list-inline-item">
            <form class="d-flex" method="POST" action="#">
                <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search">
                <input class="btn btn-outline-primary btn-sm" type="submit" value="Search"></input>
            </form>
        </li>
        </ul>
    <div class="row">
        <ul class="media-list">
            {% for proposal in proposals %}
            <li class="media card-padding">
                <div class="card {{proposal.proposal_status}}">
                    <div class="card-body">
                        {% if proposal.proposal_status == 'Draft' %}
                        <div class="m-0 pull-right mx-auto">
                            <a href="/proposal/{{proposal.id}}" class="btn btn-outline-success btn-sm" type="button"><i
                                    class="fa fa-edit"></i></a>
                        </div>
                        {% elif proposal.proposal_status == 'Approved' %}
                        <ul class="list-inline m-0 pull-right mx-auto">
                            <li class="list-inline-item">
                                <a href="/createevent/{{proposal.get_reset_token()}}" class="btn btn-outline-primary btn-sm"
                                    type="button"><i class="fa fa-check"></i></a>
                            </li>
                        </ul>
                        {% elif proposal.proposal_status == 'Rejected' %}
                        <ul class="list-inline m-0 pull-right mx-auto">
                            <li class="list-inline-item">
                                <button type="button" class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal"><i class="fa fa-trash" aria-hidden="true"></i></button>
                            </li>
                        </ul>
                        <!-- Modal -->
                        <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                    <h5 class="modal-title" id="deleteModalLabel">Delete proposal?</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                            
                                    <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <form action="{{url_for('proposals.proposalDelete', proposal_id=proposal.id)}}" method="POST">
                                        <input class="btn btn-danger" type="submit" value="Delete">
                                    </form>
                                    </div>
                                </div>
                                </div>
                            </div>
                        {% endif %}
                        <dl class="row">
                            <h5 class="card-title text-truncate"><strong>{{proposal.name}}</strong> - {{proposal.proposal_status}}</h5>
                            {% if proposal.proposal_status != 'Draft' %}
                            <span class="card-text col-sm-3">{{proposal.starting_date.strftime('%x')}} -
                                {{proposal.ending_date.strftime('%x')}}</span>
                            {% else %}
                            <span class="card-text col-sm-3">{{proposal.starting_date}} -
                                {{proposal.ending_date}}</span>
                            {% endif %}
                            <span class="card-text col-sm-7 text-truncate">
                                {{proposal.description}}
                            </span>
                        </dl>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
        <a href="/catalog/proposals" class="btn btn-default btn-block text-center"><u>More Proposals</u></a>
    </div>
</div>


<div class="dashboardEventCalendar column">
    <div class="panel panel-danger">
        <div class="panel-heading">
            <h3 class="panel-title text-center">
                <span class="glyphicon glyphicon-calendar"></span> 
                Event Calendar
            </h3>
        </div>
        <!-- Grid row -->
        <div class="col-xl-12 mt-4 mb-r">

        {% for event in events %}
            <div class="row">
                <!--Panel-->
                <div class="card card-body mb-3 pb-0">
                    <div class="media d-block d-md-flex">
                        <div class="panel panel-danger col-xl-3 ">
                            <ul class="list-inline text-center col-xl-3" style="width: 100%; ">
                                <li class="list-inline-item">
                                        <div class="panel-heading month">
                                                <div class="panel-title strong">
                                                    <h1>{{event.starting_date.strftime('%b')}}</h1>
                                                </div>
                                            </div>
                                            <div class="panel-body day text-danger">
                                                <h2>{{event.starting_date.day}}</h2>
                                            </div>
                                </li>
                                <li class="list-inline-item">
                                        <div class="panel-title strong">
                                            <h1>-</h1>
                                        </div>
                                </li>
                                <li class="list-inline-item">
                                        <div class="panel-heading month">
                                                <div class="panel-title strong">
                                                    <h1>{{event.ending_date.strftime('%b')}}</h1>
                                                </div>
                                            </div>
                                            <div class="panel-body day text-danger">
                                                <h2>{{event.ending_date.day}}</h2>
                                            </div>
                                </li>
                            </ul>
                        </div>
                        <div class="media-body ml-2">
                            <h4 class="media-heading fw-bold">
                                {{event.name}}
                            </h4>
                            <dl class="row">
                                <dt class="col-sm-4">Destination:</dt>
                                <dd class="col-sm-8">{{event.destination}}</dd>
                                
                                <dt class="col-sm-4">Assisting person: </dt>
                                <dd class="col-sm-8">{{event.assistant}}</dd>
                                
                                <dt class="col-sm-4">Class:</dt>
                                {% for class in classes %}
                                {% if class.id == event.atending_class %}
                                <dd class="col-sm-8">{{class.name}}</dd>
                                {% endif %}
                                {% endfor %}
                                <dt class="col-sm-4">Event Status:</dt>
                                <dd class="col-sm-8">{{event.event_status}}</dd>

                                <dt class="col-sm-4">Document:</dt>
                                <dd class="col-sm-8"><a href="#">{{event.document}}</a></dd>
                            </dl>
                            
                        </div>
                    </div>
                </div>
            </div>
            
            {% endfor  %}
        </div>
        <div class="text-center">
                <a href="/catalog/events" class="btn btn-default btn-block"><u>More Events</u></a>
        </div>
    </div>
</div>
<div>
        
</div>

{% endblock %}

website/templates/login.html
{% extends 'main.html' %}
{% block title %}Login Page{% endblock %}

{% block content %}
<div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="{{url_for('users.reset_request')}}">Forgot Password?</a>
            </small>
        </form>
        <div class="border-top pt-3">
                <small class="text-muted">
                    Need An Account? <a class="ml-2" href="{{ url_for('users.signup') }}">Sign Up Now</a>
                </small>
            </div>
    </div>

{% endblock %}

website/templates/prasymasForm.html
{% extends 'accounts/main.html'%}
{% load static %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{form}}

        <input type="submit" value="Submit">
    </form>
{% endblock %}

website/templates/proposal.html
{% extends 'main.html'%}
{% block title %}Proposal "{{proposal.name}}"{% endblock %}
{% block content %}
<div>
    <div class="card display-style">
        <div class="card-body">
            <h1>Proposal "{{proposal.name}}"</h1>
            <br>
            <h3>Description:</h3>
            <p>
                {{proposal.description}}
            </p>
            <br>
            <h3>Starting Date:</h3>
            <p>
                {{proposal.starting_date}}
            </p>
            <br>
            <h3>Ending Date:</h3>
            <p>
                {{proposal.ending_date}}
            </p>
            <br>
            <h3>Proposal Status:</h3>
            <p>
                {{proposal.proposal_status}}
            </p>
            <br>
            <h3>Created Date:</h3>
            <p>
                {{proposal.date_created}}
            </p>
        </div>
      </div>
      {% if user.role == 'Mokytojas' %}
      <div class="text-center">
          <a class="btn btn-outline-success" href="/proposal/{{proposal.id}}/update">Update</a>
          <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
      </div>
      {% else %}
      <form action="#" method="POST" class="text-center">
          <div class="form-group">
              <label for="sel1">Select outcome:</label>
              <select class="form-control" id="sel1" name="select">
                <option>Approve</option>
                <option>Reject</option>
              </select>
          <input type="submit" class="btn btn-outline-success mt-2" value="Confirm"></input>    
      </form>
      {% endif %}
</div>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete proposal?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <form action="{{url_for('proposals.proposalDelete', proposal_id=proposal.id)}}" method="POST">
              <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}